//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRRealTimeNotificationSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobInfo
    {
        public int JobID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> LastExecutionDate { get; set; }
        public string Status { get; set; }
    }
}
